Step 1..
tdd-reviewers/java-racing pull request #2
Opened 2023-03-30 15:35 UTC by ShimTeacher

2023-03-30 16:31 UTC, povia requested changes
전체적으로 꼼꼼하게 테스트 케이스를 설정해주신 게 좋았습니다.
몇 가지 생각해볼 점 적어두었으니 확인해주시면 감사하겠습니다~

2023-03-30 16:31 UTC, povia commented on src/test/java/SetTest.java
> +        assertThat(numbers.contains(value)).isFalse();
Integer와 String을 비교하는 거라 source에 "1"을 추가해도 테스트가 통과할 거에요.
[4.4. CSV Literals](https://www.baeldung.com/parameterized-tests-junit-5#4-csv-literals)에서처럼 delimeter를 사용해서 value, expected로 분리해보는건 어떨까요?

2023-03-30 16:31 UTC, povia commented on src/test/java/StringClassTest.java
> +        Assertions.assertThat(split).doesNotContain("3");
array의 크기 확인, 포함 여부 확인, 포함하지 말아야 할 object 확인 좋습니다

2023-03-30 16:31 UTC, povia commented on src/test/java/StringClassTest.java
> +        Assertions.assertThat(split).containsExactly(input);
👍

2023-03-30 16:31 UTC, povia commented on src/test/java/SetTest.java
> +        Assertions.assertThat(size).isInstanceOf(Integer.class);
해당 테스트의 의미인 `Set은 숫자를 잘 반환할까?`의 의미로만 접근한다면,
```suggestion
       //when
        Optional<Integer> member = numbers.stream().findAny();

        // then
        assertThat(member.isPresent()).isTrue();
        Assertions.assertThat(member.get()).isInstanceOf(Integer.class);
```
의 구조처럼 존재하는 지 확인 + 확인 후 get했을 때 같은 타입인지 확인하는 건 어떨까요?

2023-04-01 05:49 UTC, ShimTeacher commented on src/test/java/SetTest.java
> +        assertThat(numbers.contains(value)).isFalse();
delimeter로 동작을 변경했는데 괜찮은 것 같군요

2023-04-01 06:12 UTC, povia approved these changes
두 부분만 보시면 될 듯 합니다~
나머지 부분에서도 이상은 없으니 이번 단계는 여기까지 하도록 하겠습니다.

2023-04-01 06:12 UTC, povia commented on src/test/java/SetTest.java
> +import org.junit.jupiter.params.provider.ValueSource;
추가로
``` java
import java.util.Optional;
```
도 필요할 듯 합니다~

2023-04-01 06:12 UTC, povia commented on src/test/java/SetTest.java
> +    void case4(String value, boolean expected) {
``` java
@CsvSource( value= { "1:true", "4:false", "5:false" }, delimiter = ':')
    void case4(int value, boolean expected) {
```
이렇게도 둘 수 있습니다.

2023-04-01 06:14 UTC, merged